#!/usr/bin/env python3
"""Regenerate index.html by scanning this folder for topic pages.

Run this after adding/removing a .html file in this folder:
    python3 build_index.py
"""
import html
import re
from pathlib import Path

FOLDER = Path(__file__).parent
OUTPUT = FOLDER / "index.html"
SKIP = {"index.html"}

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.IGNORECASE | re.DOTALL)


def prettify_filename(stem: str) -> str:
    words = re.split(r"[-_]+", stem)
    return " ".join(w.capitalize() for w in words if w)


def get_title(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="ignore")
    match = TITLE_RE.search(text)
    if match:
        title = re.sub(r"\s+", " ", match.group(1)).strip()
        if title:
            return title
    return prettify_filename(path.stem)


def collect_pages():
    pages = []
    for path in sorted(FOLDER.glob("*.html")):
        if path.name in SKIP:
            continue
        pages.append({"file": path.name, "title": get_title(path)})
    pages.sort(key=lambda p: p["title"].lower())
    return pages


def render(pages):
    cards = "\n".join(
        f'''      <a class="card" href="{html.escape(p['file'])}">
        <span class="card-title">{html.escape(p['title'])}</span>
        <span class="card-arrow">&rarr;</span>
      </a>'''
        for p in pages
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ML Learning Notes</title>
<style>
  :root {{
    --bg: #0a0a0f; --bg2: #111118; --bg3: #18181f;
    --border: #2a2a38; --border2: #383848;
    --text: #e8e8f0; --text2: #9898b0; --text3: #5a5a70;
    --accent: #7c6af7; --accent2: #a594f9;
    --mono: 'DM Mono', 'Courier New', monospace;
    --sans: 'DM Sans', -apple-system, sans-serif;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: var(--bg); color: var(--text); font-family: var(--sans);
    min-height: 100vh; padding: 3rem 1.5rem;
  }}
  .wrap {{ max-width: 760px; margin: 0 auto; }}
  header {{ margin-bottom: 2rem; }}
  h1 {{ font-size: 1.8rem; font-weight: 300; letter-spacing: -0.02em; }}
  header p {{ color: var(--text2); font-family: var(--mono); font-size: 13px; margin-top: 6px; }}
  #search {{
    width: 100%; background: var(--bg2); border: 1px solid var(--border2);
    border-radius: 6px; padding: 10px 14px; font-family: var(--mono);
    font-size: 13px; color: var(--text); outline: none; margin-bottom: 1.5rem;
  }}
  #search:focus {{ border-color: var(--accent); }}
  .count {{ font-family: var(--mono); font-size: 12px; color: var(--text3); margin-bottom: 1rem; }}
  .grid {{ display: grid; grid-template-columns: 1fr; gap: 8px; }}
  .card {{
    display: flex; justify-content: space-between; align-items: center;
    background: var(--bg2); border: 1px solid var(--border); border-radius: 8px;
    padding: 0.9rem 1.1rem; text-decoration: none; color: var(--text);
    transition: border-color 0.15s, background 0.15s;
  }}
  .card:hover {{ border-color: var(--accent); background: var(--bg3); }}
  .card-title {{ font-size: 14px; }}
  .card-arrow {{ color: var(--text3); font-family: var(--mono); }}
  .card:hover .card-arrow {{ color: var(--accent2); }}
  .empty {{ text-align: center; padding: 2rem; color: var(--text3); font-family: var(--mono); font-size: 13px; display: none; }}
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>ML Learning Notes</h1>
    <p>{len(pages)} topics · generated by build_index.py</p>
  </header>
  <input id="search" type="text" placeholder="Filter topics..." autocomplete="off">
  <div class="grid" id="grid">
{cards}
  </div>
  <div class="empty" id="empty">No topics match your search.</div>
</div>
<script>
  const input = document.getElementById('search');
  const cards = Array.from(document.querySelectorAll('.card'));
  const empty = document.getElementById('empty');
  input.addEventListener('input', () => {{
    const q = input.value.trim().toLowerCase();
    let visible = 0;
    cards.forEach(c => {{
      const match = c.querySelector('.card-title').textContent.toLowerCase().includes(q);
      c.style.display = match ? '' : 'none';
      if (match) visible++;
    }});
    empty.style.display = visible === 0 ? 'block' : 'none';
  }});
</script>
</body>
</html>
"""


def main():
    pages = collect_pages()
    OUTPUT.write_text(render(pages), encoding="utf-8")
    print(f"Wrote {OUTPUT} with {len(pages)} topics.")


if __name__ == "__main__":
    main()
